version: "3.8"

services:
  app:
    build: .
    container_name: resume-parser
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - MONGODB_URI=${MONGODB_URI}

volumes:
  mongo-data:
